# Generated by Django 4.2 on 2025-02-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_remove_memo_created_at_remove_memo_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name_tag',
            new_name='name',
        ),
    ]
