# Generated by Django 4.2 on 2025-02-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_rename_name_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
