# Generated by Django 4.2 on 2025-02-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_alter_memo_title_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(max_length=20),
        ),
    ]
